algoritmo "somaprocedimento"
var
   x, y : inteiro
   procedimento soma (a, b : inteiro)
   inicio
         escreval("")
         escreval("Recebi o valor:", a)
         escreval("Recebi o valor:", b)
         escreval("a soma entre os valores é:", a + b)
   fimprocedimento
inicio
       escreva("Qual valor de X? ")
       leia(x)
       escreva("Qual valor de Y? ")
       leia(y)
       soma(x, y)
fimalgoritmo